# SPDX-License-Identifier: GPL-2.0-only

LINUXINCLUDE += \
		-I$(VRPC_ROOT)/include/uapi/

obj-$(CONFIG_VIRTIO_FASTRPC) += vfastrpc.o
vfastrpc-objs := dsp/virtio_fastrpc_base.o \
			  dsp/virtio_fastrpc_core.o \
			  dsp/virtio_fastrpc_mem.o \
			  dsp/virtio_fastrpc_queue.o

ifeq ($(CONFIG_COMPAT), y)
	vfastrpc-objs += dsp/adsprpc_compat.o
endif
