# SPDX-License-Identifier: GPL-2.0-only

LINUXINCLUDE += \
		-I$(VRPC_ROOT)/include/uapi/

ccflags-y += -DDSP_TRACE_INCLUDE_PATH=../../../../../../vendor/qcom/opensource/dsp-kernel/dsp

vfastrpc-objs := dsp/virtio_fastrpc_base.o \
		 dsp/virtio_fastrpc_core.o \
		 dsp/virtio_fastrpc_mem.o \
		 dsp/virtio_fastrpc_queue.o \
		 dsp/fastrpc_ioctl.o \
		 dsp/fastrpc_common.o

hfastrpc-objs := dsp/hybrid_fastrpc_vdev.o \
		 dsp/hybrid_fastrpc_core.o \
		 dsp/virtio_fastrpc_mem.o \
		 dsp/virtio_fastrpc_queue.o \
		 dsp/fastrpc_ioctl.o \
		 dsp/fastrpc_common.o \
		 dsp/adsprpc_rpmsg.o

ifeq ($(CONFIG_COMPAT), y)
  vfastrpc-objs += dsp/adsprpc_compat.o dsp/fastrpc_compat.o
  hfastrpc-objs += dsp/adsprpc_compat.o dsp/fastrpc_compat.o
endif

obj-$(CONFIG_VIRTIO_FASTRPC) += vfastrpc.o
obj-$(CONFIG_HYBRID_FASTRPC) += hfastrpc.o
