# SPDX-License-Identifier: GPL-2.0-only

export CONFIG_QCOM_ADSP_VOTE_SMP2P=m
export CONFIG_PM_SILENT_MODE=m
export CONFIG_SILENT_MODE=m
export CONFIG_MSM_S2R_WAKEUP_MARKER=m
export CONFIG_QCOM_AOP_SET_DDR=m
export CONFIG_WALLPOWER_CHARGER=m
export CONFIG_DUMP_XBL_LOG=m
